---
- type: replace
- name: docker
  version: 30.1.4
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.1.4/docker-30.1.4.tgz
  sha1: f79a70452b3ddae52f5ac78dd37ff8d9e6ec19e2
