groups:
- name: docker-boshrelease
  jobs:
  - testflight
  - testflight-pr
  - rc
  - shipit
  - major
  - minor

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: git
  type: git
  source:
    branch: tmp/kubo-ci
    private_key: ((git-ssh-key))
    uri: git@github.com:cloudfoundry-incubator/docker-boshrelease
- name: git-pull-requests
  type: pull-request
  source:
    repo: cloudfoundry-incubator/docker-boshrelease
    base: master
    private_key: ((git-ssh-key))
    access_token: ((github-token-key))
- name: version
  type: semver
  source:
    driver: gcs
    key: docker-boshrelease-version
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    initial_version: 31.0.1
- name: notify
  type: slack-notification
  source:
    url: ((build-alert-slack-url))
- name: github
  type: github-release
  source:
    access_token: ((github-kubo-gitbot-access-token))
    repository: docker-boshrelease
    user: cloudfoundry-community
- name: s3-tarball
  type: s3
  source:
    access_key_id: invalid
    bucket: docker-boshrelease
    regexp: docker-(.*).tgz
    region_name: us-east-1
    secret_access_key: invalid

jobs:
- name: testflight
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: git
        trigger: true
      name: get
    - aggregate:
      - config:
          image_resource:
            source:
              repository: starkandwayne/concourse
              tag: latest
            type: docker-image
          inputs:
          - name: git
          params: &testflight_params
            AWS_ACCESS_KEY: invalid
            AWS_SECRET_KEY: invalid
            PROXY_PRIVATE_KEY: ((docker-bosh.proxy-private-key))
            PROXY_USERNAME: ((docker-bosh.proxy-username))
            PROXY_IP: ((docker-bosh.proxy-ip))
            BOSH_CA_CERT: ((docker-bosh.ca-cert))
            BOSH_CLIENT: ((docker-bosh.client))
            BOSH_CLIENT_SECRET: ((docker-bosh.client-secret))
            BOSH_DEPLOYMENT: docker-testflighten
            BOSH_ENVIRONMENT: ((docker-bosh.environment))
            MANIFEST_OP_PATHS: ""
            MANIFEST_PATH: manifests/containers/example.yml
            MANIFEST_VARS: '--- {}'
            REPO_ROOT: git
            TEST_ERRANDS: null
          platform: linux
          run:
            args: []
            path: ./git/ci/scripts/testflight
        name: testflight
        task: testflight
      - config:
          image_resource:
            source:
              repository: starkandwayne/concourse
              tag: latest
            type: docker-image
          inputs:
          - name: git
          params:
            <<: *testflight_params
            BOSH_DEPLOYMENT: docker-swarm-testflight
            MANIFEST_PATH: manifests/swarm/docker-swarm.yml
          platform: linux
          run:
            args: []
            path: ./git/ci/scripts/testflight
        name: testflight-swarm
        task: testflight-swarm
      name: testflights
    name: main
    on_failure:
      params:
        channel: '#docker-boshrelease'
        text: '<https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|
          Concourse Failure! :sad_panda:> docker-boshrelease: testflight job failed'
      put: notify
- name: testflight-pr
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: git-pull-requests
        trigger: true
        version: every
      name: get
    - name: pending-status
      params:
        path: git-pull-requests
        status: pending
      put: git-pull-requests
    - aggregate:
      - config:
          image_resource:
            source:
              repository: starkandwayne/concourse
              tag: latest
            type: docker-image
          inputs:
          - name: git-pull-requests
          params:
            <<: *testflight_params
            BOSH_DEPLOYMENT: docker-testflight-pr
            REPO_ROOT: git-pull-requests
          platform: linux
          run:
            args: []
            path: ./git-pull-requests/ci/scripts/testflight
        name: testflight
        on_failure:
          params:
            path: git-pull-requests
            status: failure
          put: git-pull-requests
        on_success:
          params:
            path: git-pull-requests
            status: success
          put: git-pull-requests
        task: testflight
      - config:
          image_resource:
            source:
              repository: starkandwayne/concourse
              tag: latest
            type: docker-image
          inputs:
          - name: git-pull-requests
          params:
            <<: *testflight_params
            BOSH_DEPLOYMENT: docker-swarm-testflight-pr
            MANIFEST_PATH: manifests/swarm/docker-swarm.yml
            REPO_ROOT: git-pull-requests
          platform: linux
          run:
            args: []
            path: ./git-pull-requests/ci/scripts/testflight
        name: testflight-swarm
        task: testflight-swarm
      name: testflights
    - config:
        image_resource:
          source:
            repository: starkandwayne/concourse
            tag: latest
          type: docker-image
        inputs:
        - name: git-pull-requests
        outputs:
        - name: message
        platform: linux
        run:
          args:
          - -ce
          - |
            cd git-pull-requests
            pr_url=$(git config --get pullrequest.url)
            cd -
            echo "<${pr_url}|Pull request passed testflight> Merge when ready: ${pr_url}" > message/body
          path: sh
      name: pr-success-message
      task: pr-success-message
    name: main
    on_success:
      params:
        channel: '#docker-boshrelease'
        text_file: message/body
      put: notify
- name: rc
  public: true
  plan:
  - do:
    - aggregate:
      - get: git
        passed:
        - testflight
        trigger: true
      - get: version
        params:
          pre: rc
        trigger: true
    - params:
        file: version/number
      put: version
    on_failure:
      params:
        channel: '#docker-boshrelease'
        text: '<https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|
          Concourse Failure! :sad_panda:> docker-boshrelease: rc job failed'
      put: notify
- name: minor
  public: true
  plan:
  - do:
    - get: version
      params:
        bump: minor
      trigger: false
    - params:
        file: version/number
      put: version
    on_failure:
      params:
        channel: '#docker-boshrelease'
        text: '<https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|
          Concourse Failure! :sad_panda:> docker-boshrelease: minor job failed'
      put: notify
- name: major
  public: true
  plan:
  - do:
    - get: version
      params:
        bump: major
      trigger: false
    - params:
        file: version/number
      put: version
    on_failure:
      params:
        channel: '#docker-boshrelease'
        text: '<https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|
          Concourse Failure! :sad_panda:> docker-boshrelease: major job failed'
      put: notify
- name: shipit
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: version
        params:
          bump: final
        passed:
        - rc
      - get: git
        passed:
        - rc
      name: inputs
    - config:
        image_resource:
          source:
            repository: starkandwayne/concourse
            tag: latest
          type: docker-image
        inputs:
        - name: version
        - name: git
        outputs:
        - name: gh
        - name: pushme
        - name: notifications
        params:
          AWS_ACCESS_KEY: invalid
          AWS_SECRET_KEY: invalid
          BRANCH: master
          GIT_EMAIL: invalid
          GIT_NAME: invalid
          GITHUB_OWNER: cloudfoundry-community
          NOTIFICATION_OUT: notifications
          RELEASE_ROOT: gh
          REPO_OUT: pushme
          REPO_ROOT: git
          VERSION_FROM: version/number
        platform: linux
        run:
          args: []
          path: ./git/ci/scripts/shipit
      name: release
      task: release
    - name: upload-git
      params:
        rebase: true
        repository: pushme/git
      put: git
    - name: tarball
      params:
        file: gh/artifacts/docker-*.tgz
      put: s3-tarball
    - name: github-release
      params:
        body: gh/notes.md
        globs:
        - gh/artifacts/*
        name: gh/name
        tag: gh/tag
      put: github
    - name: version-bump
      params:
        bump: patch
      put: version
    - aggregate:
      - params:
          channel: '#docker-boshrelease'
          text_file: notifications/message
        put: notify
      name: notify
    on_failure:
      params:
        channel: '#docker-boshrelease'
        text: '<https://ci.kubo.sh/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|
          Concourse Failure! :sad_panda:> docker-boshrelease: shipit job failed'
      put: notify
